### ISSUE TITLE
Cannot open napari (bundled app version) on windows 11

### ISSUE THREAD

**Issue by ustcfdm** [napari/packaging#50]
## 🐛 Bug

Cannot open napari (bundled app version) on windows 11.

## To Reproduce

1. Download and install [napari bundled app version 0.4.17](https://github.com/napari/napari/releases/download/v0.4.17/napari-0.4.17-Windows-x86_64.exe) 
2. Doulbe click icon napari (0.4.17) to open.
3. A black powershell window appeared just one second then disappeared.

## Environment

CPU:	12th Gen Intel(R) Core(TM) i9-12900KF   3.19 GHz
RAM	32.0 GB 
System:    64-bit X64

Windows 11 professional
version	22H2
OS version	22621.819

**Comment by jaimergp** [comment]
Windows' conda-standalone was choosing an older menuinst for whatever reason 🤷 

* Latest available (picked by Linux and macOS): `menuinst 2.0a-38_ge820413_h24e6785 napari/label/bundle_tools_2`
* Windows: `menuinst 2.0a-20_g59bd104_h6e9b396 napari/label/bundle_tools_2`

I have checked that build 38 does work outside an installer, so I am rebuilding the conda-standalone binaries with stricter requirements. If there are no conflicts, it should be fixed in the next nightly.

**Comment by jaimergp** [comment]
Well, turns out this is becoming a rabbit hole.

- Windows builds for our menuinst have been failing since build 21. In other words, last good one was build 20. That explains why the solver chooses build 20: it's the only one available!
- Why is this happening? The CI was all green but it's a false positive! The runner just gave up and said "ye, this is good". I'll need to add some extra checks for artifact existence.
- The errors are logging-related. Thousands of blocks like this:

```
  --- Logging error ---
  Traceback (most recent call last):
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\logging\__init__.py", line 1103, in emit
      stream.write(msg + self.terminator)
  ValueError: underlying buffer has been detached
  Call stack:
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
      main()
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\build_meta.py", line 412, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 33, in <module>
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Miniconda3\conda-bld\menuinst_1670499904820\_h_env\lib\site-packages\wheel\bdist_wheel.py", line 399, in run
      log.info(f"removing {self.bdist_dir}")
  Message: 'removing build\\bdist.win-amd64\\wheel'
  Arguments: ()
```

I am now debugging locally to see what's causing this. `setuptools`? `wheel`?

**Comment by jaimergp** [comment]
Hm, in a new attempt this is not observed. But the process dies after running the build script (maybe in the linkage analysis?):

```
INFO:conda_build.build:Packaging menuinst
Packaging menuinst
INFO:conda_build.build:Packaging menuinst-2.0a-38_ge820413_h6e9b396
Packaging menuinst-2.0a-38_ge820413_h6e9b396
compiling .pyc files...
number of files: 47
Error: Process completed with exit code -1.
```

**Comment by jaimergp** [comment]
I _think_ I finished the work needed to fix this. We'll be able to tell in the nightlies of today.

**Comment by jaimergp** [comment]
Btw, for the curious visitors:

- It had to do with a rare bug in conda-build, which choked on the OSX launchers at the linkage analysis phase on Windows. This made it crash with exit code -1. [Reported here](https://github.com/conda/conda-build/issues/4684).
- The CI scripts checked for exit code >= 1, which ignored -1 and thus returned a green step. [Reported here](https://github.com/conda-forge/conda-smithy/pull/1704).

**Comment by jaimergp** [comment]
With the build issues solved and the latest menuinst being deployed on our installers, the shortcuts include the [env var mitigations](https://github.com/napari/napari/blob/e89bb038bbd864454364eee2af218f236f275fb4/resources/conda_menu_config.json#L20) and are no longer affected by PYTHONHOME or PYTHONPATH setups. Yesterday's nightlies (~11h ago) contain the fixes.

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/2559438/209326615-45b2c5a0-4ff1-4929-9375-63ff7839ed06.png">

Thanks for the report @ustcfdm, this led me to find some issues in the pipelines that needed fixes! Closing this now.
