### ISSUE TITLE
Pydantic error when launching napari via installed constructor bundle

### ISSUE THREAD

**Issue by ctrueden** [napari/packaging#80]
I installed the napari-0.4.18 Linux constructor bundle. When I try to run the installed napari-0.4.18 directly, here's what I see:
```
$ ~/.local/napari-0.4.18/envs/napari-0.4.18/bin/napari
/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/bin/napari", line 6, in <module>
    from napari.__main__ import main
  File "/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/napari/__main__.py", line 17, in <module>
    from napari.utils.translations import trans
  File "/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/napari/utils/__init__.py", line 2, in <module>
    from napari.utils.colormaps import Colormap
  File "/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from napari.utils.colormaps.colormap import Colormap
  File "/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/napari/utils/colormaps/colormap.py", line 9, in <module>
    from napari.utils.events import EventedModel
  File "/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/napari/utils/events/__init__.py", line 17, in <module>
    from napari.utils.events.evented_model import EventedModel
  File "/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/napari/utils/events/evented_model.py", line 66, in <module>
    class EventedMetaclass(main.ModelMetaclass):
  File "/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/pydantic/_migration.py", line 289, in wrapper
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'pydantic._migration' has no attribute 'ModelMetaclass'
```

The napari 0.4.18 I have installed into a regular conda environment (not via the constructor installer) launches successfully.

It seems pretty clear that the problem is that the constructor bundle installs pydantic 2, whereas napari still works with pydantic 1:
```
$ find ~/mambaforge/envs/napari ~/.local/napari-0.4.18 -name 'pydantic*.dist-info' -type d
/home/curtis/mambaforge/envs/napari/lib/python3.9/site-packages/pydantic-1.10.11.dist-info
/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/pydantic-2.0.1.dist-info
/home/curtis/.local/napari-0.4.18/envs/napari-0.4.18/lib/python3.9/site-packages/pydantic_core-2.0.1.dist-info
```

But I could paste a more complete diff of my two environments if that would be helpful.

**Comment by jaimergp** [comment]
Yes, we need to regenerate the installers to accommodate the new version constraints. I am waiting for a couple PRs to be merged, but should be ready this week. I'll let you know when they are available!

**Comment by jaimergp** [comment]
Check now @ctrueden: https://github.com/napari/napari/releases/tag/v0.4.18

**Comment by ctrueden** [comment]
Awesome @jaimergp, the new bundle works nicely on my machine. It also made a `~/.local/share/applications/napari-0418_napari-0418.desktop` so that napari appears as a normal application. :star2: 

I was also able to install the napari-imagej plugin using the graphical plugin installer. But when OpenJDK spins up, it crashes. 😭 But on the napari packaging side, this issue is definitely resolved! :+1:

**Comment by jaimergp** [comment]
Do you have an error message for the OpenJDK error? You should be able to launch napari from its internal conda environment (somewhere in ~/.local).

**Comment by ctrueden** [comment]
@jaimergp It's a SIGSEGV. If you're interested in digging, the issue is at imagej/napari-imagej#269.
